name: E2E Insomnia Action Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  e2e-insomnia-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - name: "Basic Test Suite"
            command: "test"
            identifier: "New Suite"
            env: "Base Environment"
            working-directory: "test-data/sample-export-test.yaml"
          - name: "Collection Run"
            command: "collection"
            identifier: "Sample Collection"
            env: "Base Environment"
            working-directory: "test-data/sample-export.yaml"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Insomnia Run Action (${{ matrix.scenario.name }})
        uses: scarowar/insomnia-run@feat/action
        with:
          command: ${{ matrix.scenario.command }}
          identifier: ${{ matrix.scenario.identifier }}
          environment: ${{ matrix.scenario.env }}
          working-directory: ${{ matrix.scenario.working-directory }}
          pr-comment: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
